/* NovaDesk bootstrap with Games Hub shortcut added. */
(function(){
  const state=NovaState.state,start=document.getElementById("start-menu"),appsHost=document.getElementById("start-apps"),startSearch=document.getElementById("start-search"),taskbarSearch=document.getElementById("taskbar-search");
  function boot(){document.documentElement.dataset.theme=state.persisted.theme||"light";renderDesktopIcons();renderStartApps();wire();clock();setInterval(clock,1000);setTimeout(()=>document.getElementById("boot").classList.add("done"),500)}
  function renderDesktopIcons(){const host=document.getElementById("desktop-icons");host.innerHTML="";["files","browser","games","settings","terminal"].forEach(id=>{const app=NovaApps.get(id);if(!app)return;const b=document.createElement("button");b.className="desktop-icon";b.innerHTML=`<span class="icon">${app.icon}</span><span>${app.name}</span>`;b.onclick=()=>NovaWindows.openApp(id);host.appendChild(b)})}
  function renderStartApps(filter=""){appsHost.innerHTML="";NovaApps.all().filter(a=>!a.hidden).filter(a=>(a.name+" "+a.description).toLowerCase().includes(filter.toLowerCase())).forEach(app=>{const b=document.createElement("button");b.className="start-app";b.innerHTML=`<span class="icon">${app.icon}</span><b>${app.name}</b><small>${app.description}</small>`;b.onclick=()=>{toggleStart(false);NovaWindows.openApp(app.id)};appsHost.appendChild(b)})}
  function toggleStart(force){state.startOpen=typeof force==="boolean"?force:!state.startOpen;start.classList.toggle("hidden",!state.startOpen);if(state.startOpen){startSearch.value="";renderStartApps();setTimeout(()=>startSearch.focus(),50)}}
  function clock(){document.getElementById("clock").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}
  function runSearch(value){const v=value.trim();if(!v)return;const app=NovaApps.all().find(a=>!a.hidden&&(a.name+" "+a.description).toLowerCase().includes(v.toLowerCase()));if(app)NovaWindows.openApp(app.id);else NovaBrowser.open(v);taskbarSearch.value=""}
  function wire(){document.getElementById("start-button").onclick=()=>toggleStart();document.getElementById("start-close").onclick=()=>toggleStart(false);document.getElementById("theme-toggle").onclick=()=>{state.persisted.theme=state.persisted.theme==="dark"?"light":"dark";NovaState.save();document.documentElement.dataset.theme=state.persisted.theme};startSearch.oninput=()=>renderStartApps(startSearch.value);taskbarSearch.addEventListener("pointerdown",e=>e.stopPropagation());taskbarSearch.addEventListener("click",e=>{e.stopPropagation();taskbarSearch.focus()});taskbarSearch.onkeydown=e=>{if(e.key==="Enter")runSearch(taskbarSearch.value)};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();taskbarSearch.focus();taskbarSearch.select()}if(e.key==="Escape")toggleStart(false)});document.getElementById("desktop").oncontextmenu=e=>{if(e.target.closest(".window")||e.target.closest(".taskbar"))return;e.preventDefault();NovaContextMenu.show(e.clientX,e.clientY,[{label:"Open Games Hub",icon:"🎮",action:()=>NovaWindows.openApp("games")},{label:"Open File Explorer",icon:"📁",action:()=>NovaWindows.openApp("files")},{label:"Open Browser",icon:"🌐",action:()=>NovaWindows.openApp("browser")},{label:"Open Settings",icon:"⚙️",action:()=>NovaWindows.openApp("settings")},"divider",{label:"New text file",icon:"📄",action:()=>{const n=prompt("File name","Desktop Note.txt");if(n)NovaState.createFsItem("/Desktop",n,"file","New desktop note")}}])}}
  boot();
})();
